server:
  port: 9090

jwt:
  secret: ${JWT_SECRET:sOt8xknkN4pDggxLUqNV5OBTijY8IYm1PRBRcP9T5Bw=}
  expiration: ${JWT_EXPIRATION:3600000}

spring:
  application:
    name: healthconnect-api-gateway
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  cloud:
    gateway:
      routes:
        # Auth Service
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - PreserveHostHeader

        # Patient Service
        - id: patient-service
          uri: ${PATIENT_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/patients/**, /api/v1/doctype/**, /api/v1/medical-records/**, /api/v1/replication/**
          filters:
            - AuthenticationFilter

        # Storage Service
        - id: storage-service
          uri: ${STORAGE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/storage/**
          filters:
            - AuthenticationFilter

        # Audit Hub Service
        - id: audit-hub-service
          uri: ${AUDIT_SERVICE_URL:http://localhost:8000}
          predicates:
            - Path=/api/v1/audit/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      show-details: always # Optional: gives more info about disk, db, etc.